### ISSUE TITLE
Unpublished item should not be deleted, it shall only be marked as unpublished in Recombee

### ISSUE THREAD

**Issue by OndraFiedler** [kontent-ai/example-integration-recombee#3]
### Description

Currently, the `DeleteItem` endpoint of the Recombee API is being called in a webhook in case a post is unpublished:
- https://github.com/Kentico/kontent-example-integration-recombee/blob/44bf033ca3e64aadc56737703e1fe12b54f5719e/src/lambda/model/recombee-client.ts#L104
- https://github.com/Kentico/kontent-example-integration-recombee/blob/c35289ff1324337cb226ed49963abefc931cd850/src/lambda/recombee-sync-webhook.ts#L93
.

However, the post shall be only marked as unpublished using an item property, as deleting the item also removes all the associated interactions from Recombee.
See https://docs.recombee.com/reql_filtering_and_boosting.html#handling-deleted-items.

**Comment by strizr** [comment]
I'll take a look, thanks!

**Comment by strizr** [comment]
@OndraFiedler we discussed this internally, and although we understand what's happening, we don't want to enforce a set model property onto the user, that he needs to filter by (e.g. if we decide that everybody has to have a "published" property in their model and they will ALWAYS need to filter by that property to recommend valid content). This is just a sample integration, so the customer is always free to update it as they see fit, but I would almost see this as a feature to be added directly into recombee. It could have a special method for a "soft" delete that will just hide the data instead of removing them so the models are not being affected and the user experience is not affected. That being said, I'll link the docs about handling deleted items into the readme.
